Merge LCS into Master
2202Programming/Mercy pull request #6
Opened 2016-09-30 22:52 UTC by TomRaven

2016-09-30 22:58 UTC, Minnow42 commented on Algrothms/String/LongestCommonSubstring/LongestCommonSubstring.java
> +    private boolean GlobalAllignment;
Misspelled alignment

2016-09-30 22:58 UTC, Minnow42 commented on Algrothms/String/LongestCommonSubstring/LongestCommonSubstring.java
> +     * Creates a LCS object with default score values, this can be used
Run-on sentence

2016-09-30 22:59 UTC, Minnow42 commented on Algrothms/String/LongestCommonSubstring/LongestCommonSubstring.java
> +     * Runs the program all interactive like.
Clarify this please

2016-09-30 22:59 UTC, Minnow42 commented on Algrothms/String/LongestCommonSubstring/LongestCommonSubstring.java
> +            System.out.print("Do you want to try again (y/n) ");
Missing a question mark

2016-09-30 23:00 UTC, Minnow42 commented on Algrothms/String/LongestCommonSubstring/README.md
> +Used commonly in bioinformatics to find common patterns in many sequences of DNA, there are several different variations on this but they can all be built using the same basis.
Another run-on

2016-09-30 23:00 UTC, Minnow42 commented on Algrothms/String/LongestCommonSubstring/README.md
> +It has a time Complexity of O(nm), and a space complexity of O(nm), further optimizations could be used to improve the space efficiency to O(n + m)
Run-on

2016-09-30 23:00 UTC, Minnow42 requested changes
See comments

2016-09-30 23:37 UTC, TomRaven commented on Algrothms/String/LongestCommonSubstring/LongestCommonSubstring.java
> +     * Creates a LCS object with default score values, this can be used
WHO CARES

2016-10-03 21:06 UTC, Minnow42 approved these changes
ok sure tommy

2016-10-03 21:09 UTC, merged